
#ifndef LG_BACKUP_ITEMS_H
#define LG_BACKUP_ITEMS_H

/*
* MISC Partition Usage
+-------+------------------------+----------+
|MISC(0~4)  |  FRST(8)  |  MEID(12)  |  NVCRC(16)  |  ESN (20)  |  WLAN_MAC(24)  |  PF_NIC(28)  
|MSMPID(32)|USBID(36)|WEBSID(40)| XCALBACKUP(44)
+-------+------------------------+----------+
MISC		: Recovery Message 저장용
FRST		: Factory reset flag
MEID		: NV_MEID_I backup
NVCRC		: NV crc data backup
ESN		: NV_ESN_I backup
PID			: NV_FACTORY_INFO_I backup
WLAN_MAC	: NV_WLAN_MAC_ADDRESS_I backup
PF_NIC		: NV_LG_LTE_PF_NIC_MAC_I backup
WEB_SID		: WEB DOWNLOAD SID REMARK
XCALBACKUP	: RF CAL Golden Copy 저장용
*/

/*
 * page offset in the partition
 */
#define PTN_FRST_PERSIST_OFFSET_IN_MISC_PARTITION   8
#define PTN_MEID_PERSIST_OFFSET_IN_MISC_PARTITION   12
#ifdef CONFIG_LGE_DLOAD_FACTORY_RESET
#define PTN_DLOAD_FRST_PERSIST_OFFSET_IN_MISC_PARTITION  16
#else
#define PTN_NVCRC_PERSIST_OFFSET_IN_MISC_PARTITION  16
#endif
#define PTN_ESN_PERSIST_OFFSET_IN_MISC_PARTITION   20
#if 1//LGE_MAC_ADDRESS_BACKUP
#define PTN_WLAN_MAC_PERSIST_OFFSET_IN_MISC_PARTITION  24
#define PTN_PF_NIC_MAC_PERSIST_OFFSET_IN_MISC_PARTITION  28
#endif
#define PTN_PID_PERSIST_OFFSET_IN_MISC_PARTITION    32
#if defined (CONFIG_LGE_LCD_K_CAL)
#define PTN_LCD_K_CAL_OFFSET_IN_MISC_PARTITION  36
#else
#define PTN_USBID_PERSIST_OFFSET_IN_MISC_PARTITION  36
#endif
#define PTN_WEB_SID_PERSIST_OFFSET_IN_MISC_PARTITION 40
#define PTN_XCAL_OFFSET_IN_MISC_PARTITION           44

#ifdef CONFIG_LGE_USB_ACCESS_LOCK
#define PTN_USB_ACCESS_LOCK_PERSIST_OFFSET_IN_MISC_PARTITION   2048
#define PTN_USB_LOCK_KEY_PERSIST_OFFSET_IN_MISC_PARTITION   2052
#define PTN_USB_UNLOCK_FAIL_CNT_PERSIST_OFFSET_IN_MISC_PARTITION   2056

#define PTN_SRD_BACKUP_OFFSET_IN_MISC_PARTITION     2088
#else
//LGE_CHANGE_S [US730] [TestMode] [jinhwan.do@lge.com] 2012-02-07, LG DIAG porting of SRD .
#define PTN_SRD_BACKUP_OFFSET_IN_MISC_PARTITION     2048  // CONFIG_LGE_DIAG_SRD
//LGE_CHANGE_S [US730] [TestMode] [jinhwan.do@lge.com] 2012-02-07, LG DIAG porting of SRD .
#endif
//[U0] [ro.crypto.keyfile.userdata] hk.song@lge.com 2012-06-08
#define PTN_NATIVE_ENCRYPTION_OFFSET_IN_MISC_PARTITION	4096
//[U0] [ro.ssbd.session] hk.song@lge.com 2012-06-08
#define PTN_SDCARD_ENCRYPTION_OFFSET_IN_MISC_PARTITION	4136

#define PTN_FRST_PERSIST_POSITION_IN_MISC_PARTITION     (512*PTN_FRST_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_MEID_PERSIST_POSITION_IN_MISC_PARTITION     (512*PTN_MEID_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_ESN_PERSIST_POSITION_IN_MISC_PARTITION     (512*PTN_ESN_PERSIST_OFFSET_IN_MISC_PARTITION)
#ifdef CONFIG_LGE_DLOAD_FACTORY_RESET
#define PTN_DLOAD_FRST_PERSIST_POSITION_IN_MISC_PARTITION    (512*PTN_DLOAD_FRST_PERSIST_OFFSET_IN_MISC_PARTITION)
#else
#define PTN_NVCRC_PERSIST_POSITION_IN_MISC_PARTITION    (512*PTN_NVCRC_PERSIST_OFFSET_IN_MISC_PARTITION)
#endif
#if 1//LGE_MAC_ADDRESS_BACKUP
#define PTN_WLAN_MAC_PERSIST_POSITION_IN_MISC_PARTITION (512*PTN_WLAN_MAC_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_PF_NIC_MAC_PERSIST_POSITION_IN_MISC_PARTITION  (512*PTN_PF_NIC_MAC_PERSIST_OFFSET_IN_MISC_PARTITION)
#endif
#define PTN_PID_PERSIST_POSITION_IN_MISC_PARTITION      (512*PTN_PID_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_USBID_PERSIST_POSITION_IN_MISC_PARTITION    (512*PTN_USBID_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_WEB_SID_POSITION_IN_MISC_PARTITION          (512*PTN_WEB_SID_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_XCAL_POSITION_IN_MISC_PARTITION             (512*PTN_XCAL_OFFSET_IN_MISC_PARTITION)
//LGE_CHANGE_S [US730] [TestMode] [jinhwan.do@lge.com] 2012-02-07, LG DIAG porting of SRD .
#define PTN_SRD_BACKUP_POSITION_IN_MISC_PARTITION       (512*PTN_SRD_BACKUP_OFFSET_IN_MISC_PARTITION) // CONFIG_LGE_DIAG_SRD
//LGE_CHANGE_S [US730] [TestMode] [jinhwan.do@lge.com] 2012-02-07, LG DIAG porting of SRD .

#if defined (CONFIG_LGE_LCD_K_CAL)
#define PTN_LCD_K_CAL_POSITION_IN_MISC_PARTITION     (512*PTN_LCD_K_CAL_OFFSET_IN_MISC_PARTITION)
#endif

#ifdef CONFIG_LGE_USB_ACCESS_LOCK
#define PTN_USB_ACCESS_LOCK_PERSIST_POSITION_IN_MISC_PARTITION (512*PTN_USB_ACCESS_LOCK_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_USB_LOCK_KEY_PERSIST_POSITION_IN_MISC_PARTITION (512*PTN_USB_LOCK_KEY_PERSIST_OFFSET_IN_MISC_PARTITION)
#define PTN_USB_UNLOCK_FAIL_CNT_PERSIST_POSITION_IN_MISC_PARTITION (512*PTN_USB_UNLOCK_FAIL_CNT_PERSIST_OFFSET_IN_MISC_PARTITION)
#endif
//[U0] [ro.crypto.keyfile.userdata] hk.song@lge.com 2012-06-08
#define PTN_NATIVE_ENCRYPTION_POSITION_IN_MISC_PARTITION	(512*PTN_NATIVE_ENCRYPTION_OFFSET_IN_MISC_PARTITION)
//[U0] [ro.ssbd.session] hk.song@lge.com 2012-06-08
#define PTN_SDCARD_ENCRYPTION_POSITION_IN_MISC_PARTITION	(512*PTN_SDCARD_ENCRYPTION_OFFSET_IN_MISC_PARTITION)

/*
 * command codes for the backup operation
 */
#define CALBACKUP_GETFREE_SPACE         0
#define CALBACKUP_CAL_READ              1
#define CALBACKUP_MEID_READ             2
#define CALBACKUP_MEID_WRITE            4
#define CALBACKUP_ERASE                 5
#define CALBACKUP_CAL_WRITE             6
#define NVCRC_BACKUP_READ               7
#define NVCRC_BACKUP_WRITE              8
#define PID_BACKUP_READ                 9
#define PID_BACKUP_WRITE                10

/* ADD 0015981: [MANUFACTURE] BACK UP MAC ADDRESS NV */
#if 1//LGE_MAC_ADDRESS_BACKUP
#define WLAN_MAC_ADDRESS_BACKUP_READ	11
#define WLAN_MAC_ADDRESS_BACKUP_WRITE	12
#define PF_NIC_MAC_BACKUP_READ			13
#define PF_NIC_MAC_BACKUP_WRITE			14
#define USBID_REMOTE_WRITE              15
#endif

#if 1 // def LG_FW_WEB_DOWNLOAD
#define WEB_SID_REMARK_READ             16
#define WEB_SID_REMARK_WRITE            17
#endif


#define CALBACKUP_ESN_READ              18
#define CALBACKUP_ESN_WRITE             19

#ifdef CONFIG_LGE_USB_ACCESS_LOCK
#define USB_ACCESS_LOCK_READ            20
#define USB_ACCESS_LOCK_WRITE           21
#define USB_LOCK_KEY_READ               22
#define USB_LOCK_KEY_WRITE              23
#define USB_UNLOCK_FAIL_CNT_READ        24
#define USB_UNLOCK_FAIL_CNT_WRITE       25
#endif

#define CALBACKUP_CALFILE		0
#define CALBACKUP_MEIDFILE		1


/*
 * set magic code 8 byte for validation
 */
#define MEID_MAGIC_CODE 0x4D4549444D454944 /*MEIDMEID*/
#define MEID_MAGIC_CODE_SIZE 8

#define ESN_MAGIC_CODE 0x45534E5F /*ESN_*/
#define ESN_MAGIC_CODE_SIZE 4

#define FACTORYINFO_MAGIC_CODE 0x5049445F /*PID_*/
#define FACTORYINFO_MAGIC_CODE_SIZE 4

#define WLAN_MAGIC_CODE 0x574C /*WL*/
#define PFNIC_MAGIC_CODE 0x5046 /*PF*/
#define MACADDR_MAGIC_CODE_SIZE 2

#define MEIDBACKUP_SECTOR_SIZE		1

#define USBID_MAGIC_CODE 0x55534249 /*USBI*/
#define USBID_MAGIC_CODE_SIZE 4

#ifdef CONFIG_LGE_USB_ACCESS_LOCK
#define USB_ACCESS_LOCK_MAGIC_CODE            0x5553424C4F434B /*USBLOCK*/
#define USB_ACCESS_LOCK_MAGIC_CODE_SIZE       7
#define USB_LOCK_KEY_MAGIC_CODE               0x4C4B4559 /*LKEY*/
#define USB_LOCK_KEY_MAGIC_CODE_SIZE          4
#define USB_UNLOCK_FAIL_CNT_MAGIC_CODE        0x4641494C434E54 /*FAILCNT*/
#define USB_UNLOCK_FAIL_CNT_MAGIC_CODE_SIZE   7
#endif

/*
 * actual item size declaration, smem allocation size should be 64-bit aligned
 */
//#define MEIDBACKUP_BYTES_SIZE				8
#define MEID_BACKUP_SIZE					8
#define MEID_BACKUP_64BIT_ALIGNED_SIZE	(MEID_MAGIC_CODE_SIZE+MEID_BACKUP_SIZE)

#define ESN_BACKUP_SIZE					4
#define ESN_BACKUP_64BIT_ALIGNED_SIZE	(ESN_MAGIC_CODE_SIZE+ESN_BACKUP_SIZE)

#define USBID_BACKUP_SIZE					4
#define USBID_BACKUP_64BIT_ALIGNED_SIZE	(USBID_MAGIC_CODE_SIZE+USBID_BACKUP_SIZE)

#define FACTORYINFO_BACKUP_SIZE					100
#define FACTORYINFO_BACKUP_64BIT_ALIGNED_SIZE	(FACTORYINFO_MAGIC_CODE_SIZE + FACTORYINFO_BACKUP_SIZE)

/* ADD 0015981: [MANUFACTURE] BACK UP MAC ADDRESS NV */
#if 1//LGE_MAC_ADDRESS_BACKUP
#define MACADDR_BACKUP_SIZE					6
#define MACADDR_BACKUP_64BIT_ALIGNED_SIZE	(MACADDR_MAGIC_CODE_SIZE + MACADDR_BACKUP_SIZE)
#endif

#ifdef CONFIG_LGE_USB_ACCESS_LOCK
#define USB_ACCESS_LOCK_BACKUP_SIZE            		1
#define USB_ACCESS_LOCK_BACKUP_64BIT_ALIGNED_SIZE	(USB_ACCESS_LOCK_MAGIC_CODE_SIZE+USB_ACCESS_LOCK_BACKUP_SIZE)
#define USB_LOCK_KEY_BACKUP_SIZE                20
#define USB_LOCK_KEY_BACKUP_64BIT_ALIGNED_SIZE	(USB_LOCK_KEY_MAGIC_CODE_SIZE+USB_LOCK_KEY_BACKUP_SIZE)
#define USB_UNLOCK_FAIL_CNT_BACKUP_SIZE        			1
#define USB_UNLOCK_FAIL_CNT_BACKUP_64BIT_ALIGNED_SIZE	(USB_UNLOCK_FAIL_CNT_MAGIC_CODE_SIZE+USB_UNLOCK_FAIL_CNT_BACKUP_SIZE)
#endif

//1 2012.06.08 current smem_alloc size is 8383
// sizeof(calBackupData) : 0x200F (8,207)
// smem alloc without calbackup : 0xB0 (176)
//#define BACKUP_TOTAL_SIZE 44932 //2011.06.23 current smem_alloc size
#define BACKUP_TOTAL_SIZE 8383

#endif /* LG_BACKUP_ITEMS_H */


